export const dynamic = "force-dynamic"
import { type NextRequest, NextResponse } from "next/server"
import { generateText } from "ai"
import { createClient } from "@/lib/supabase/server"
import { groqProvider, FAST_GROQ_MODEL } from "@/lib/ia/groq"
import * as fal from "@fal-ai/serverless-client"

// Configure FAL client
fal.config({
  credentials: process.env.FAL_KEY,
})

async function generateImageWithFal(prompt: string): Promise<string> {
  try {
    console.log("[v0] ==========================================")
    console.log("[v0] Generating image with FAL.ai")
    console.log("[v0] FAL_KEY configured:", !!process.env.FAL_KEY)
    console.log("[v0] FAL_KEY length:", process.env.FAL_KEY?.length || 0)
    console.log("[v0] Prompt:", prompt.substring(0, 200) + "...")

    const result: any = await fal.subscribe("fal-ai/flux/dev", {
      input: {
        prompt,
        image_size: "square_hd",
        num_inference_steps: 28,
        guidance_scale: 3.5,
        num_images: 1,
        enable_safety_checker: false,
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === "IN_PROGRESS") {
          console.log("[v0] FAL generation progress:", update.logs?.map((l: any) => l.message).join("\n"))
        }
      },
    })

    console.log("[v0] FAL result received:")
    console.log("[v0] - result exists:", !!result)
    console.log("[v0] - result.data exists:", !!result?.data)
    console.log("[v0] - result.data type:", typeof result?.data)
    console.log("[v0] - result.images exists:", !!result?.images)
    console.log("[v0] - result.data.images exists:", !!result?.data?.images)

    // FAL puede devolver imágenes en result.images o result.data.images
    const images = result?.images || result?.data?.images

    console.log("[v0] - images found:", !!images)
    console.log("[v0] - images length:", images?.length || 0)

    if (!images || images.length === 0) {
      console.error("[v0] ❌ FAL did not return images")
      console.error("[v0] Full result keys:", Object.keys(result || {}))
      console.error("[v0] Full result:", JSON.stringify(result, null, 2).substring(0, 1000))
      throw new Error("No image generated by FAL - check server logs for full response")
    }

    const imageUrl = images[0].url
    console.log("[v0] ✅ Image URL received:", imageUrl?.substring(0, 100))
    console.log("[v0] ==========================================")

    return imageUrl
  } catch (error) {
    console.error("[v0] ❌ FAL generation error:", error)
    if (error instanceof Error) {
      console.error("[v0] Error message:", error.message)
      console.error("[v0] Error stack:", error.stack)
    }
    throw error
  }
}

async function generateFloorPlanPromptWithGroq(
  area: string,
  habitaciones: string,
  banos: string,
  preferencias: string,
  layoutStyle: string
): Promise<string> {
  try {
    const { text } = await generateText({
      model: groqProvider(FAST_GROQ_MODEL),
      prompt: `Eres un experto en arquitectura y diseño de planos. Genera un prompt detallado en inglés para crear un plano arquitectónico con estas especificaciones:

- Área total: ${area}m²
- ${habitaciones} dormitorios
- ${banos} baños
- Estilo de distribución: ${layoutStyle}
- Preferencias: ${preferencias || "Diseño moderno y funcional"}

IMPORTANTE: Responde SOLO con el prompt en inglés, sin explicaciones adicionales.

El prompt debe describir un plano arquitectónico profesional visto desde arriba (floor plan) que incluya:
1. Distribución clara de habitaciones
2. Puertas y ventanas indicadas
3. Mobiliario básico representativo
4. Etiquetas de zonas
5. Estilo arquitectónico limpio y profesional

Genera el prompt para la IA de imágenes:`,
    })

    return text.trim()
  } catch (error) {
    console.error("[v0] Groq prompt generation error:", error)
    throw error
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    if (!supabase) {
      return NextResponse.json({ error: "Configuración de servidor incompleta" }, { status: 500 })
    }

    const {
      data: { session },
    } = await supabase.auth.getSession()

    if (!session) {
      return NextResponse.json({ error: "No autorizado" }, { status: 401 })
    }

    const { area, habitaciones, banos, preferencias } = await request.json()

    console.log("[v0] Generating distributions with Groq + FAL:", { area, habitaciones, banos, preferencias })

    const distributions: string[] = []

    const layouts = [
      "distribución tradicional con pasillos y zonas separadas",
      "distribución abierta tipo loft con espacios conectados",
      "distribución optimizada con zonas bien definidas y funcionales",
    ]

    for (let i = 0; i < 3; i++) {
      try {
        console.log(`[v0] ========== Generating distribution ${i + 1}/${3} ==========`)

        // Step 1: Generate detailed prompt with Groq
        console.log(`[v0] Step 1: Generating prompt with Groq for layout: ${layouts[i]}`)
        const imagePrompt = await generateFloorPlanPromptWithGroq(
          area,
          habitaciones,
          banos,
          preferencias,
          layouts[i]
        )

        console.log(`[v0] Generated prompt: ${imagePrompt.substring(0, 150)}...`)

        // Step 2: Generate image with FAL
        console.log(`[v0] Step 2: Generating image with FAL`)
        const imageUrl = await generateImageWithFal(
          `Architectural floor plan, top-down view: ${imagePrompt}. Clean professional architectural drawing style, black lines on white background, labeled rooms, furniture outlines, doors and windows indicated.`
        )

        distributions.push(imageUrl)
        console.log(`[v0] ✅ Distribution ${i + 1} generated successfully`)

        // Add delay between requests to avoid rate limits
        if (i < 2) {
          console.log(`[v0] Waiting 2s before next generation...`)
          await new Promise((resolve) => setTimeout(resolve, 2000))
        }
      } catch (error) {
        console.error(`[v0] ❌ Error generating distribution ${i + 1}:`, error)

        // If one fails, continue with others
        if (distributions.length === 0 && i === 2) {
          // If all failed, throw error
          throw error
        }
      }
    }

    if (distributions.length === 0) {
      throw new Error("No se pudo generar ninguna distribución")
    }

    console.log(`[v0] Successfully generated ${distributions.length} distributions`)

    return NextResponse.json({
      distributions,
      message: `${distributions.length} distribuciones generadas exitosamente con Groq + FAL`,
    })
  } catch (error) {
    console.error("[v0] Error generating distributions:", error)

    let errorMessage = "Error desconocido"
    if (error instanceof Error) {
      errorMessage = error.message

      // Provide helpful error messages
      if (errorMessage.includes("rate limit")) {
        errorMessage = "Límite de peticiones alcanzado. Espera unos minutos e inténtalo de nuevo."
      } else if (errorMessage.includes("API key") || errorMessage.includes("credentials")) {
        errorMessage = "Error de autenticación con FAL. Verifica que FAL_KEY esté configurada correctamente."
      } else if (errorMessage.includes("timeout")) {
        errorMessage = "Tiempo de espera agotado. La generación tarda aproximadamente 30-60 segundos."
      } else if (errorMessage.includes("No image generated")) {
        errorMessage = "FAL no generó imágenes. Verifica los logs del servidor para más detalles."
      }
    }

    return NextResponse.json(
      { error: `Error al generar distribuciones: ${errorMessage}` },
      { status: 500 },
    )
  }
}
