export const SUPPORTED_COUNTRIES = [
  "España",
  "Francia",
  "Portugal",
  "Italia",
  "Alemania",
  "Reino Unido",
  "Estados Unidos",
  "México",
  "Argentina",
  "Chile",
  "Colombia",
  "Perú",
] as const

export type SupportedCountry = (typeof SUPPORTED_COUNTRIES)[number]

export const PROVINCES_BY_COUNTRY: Record<SupportedCountry, string[]> = {
  España: [
    "A Coruña",
    "Álava",
    "Albacete",
    "Alicante",
    "Almería",
    "Asturias",
    "Ávila",
    "Badajoz",
    "Barcelona",
    "Burgos",
    "Cáceres",
    "Cádiz",
    "Cantabria",
    "Castellón",
    "Ciudad Real",
    "Córdoba",
    "Cuenca",
    "Girona",
    "Granada",
    "Guadalajara",
    "Guipúzcoa",
    "Huelva",
    "Huesca",
    "Islas Baleares",
    "Jaén",
    "La Rioja",
    "Las Palmas",
    "León",
    "Lleida",
    "Lugo",
    "Madrid",
    "Málaga",
    "Murcia",
    "Navarra",
    "Ourense",
    "Palencia",
    "Pontevedra",
    "Salamanca",
    "Santa Cruz de Tenerife",
    "Segovia",
    "Sevilla",
    "Soria",
    "Tarragona",
    "Teruel",
    "Toledo",
    "Valencia",
    "Valladolid",
    "Vizcaya",
    "Zamora",
    "Zaragoza",
  ],
  Francia: ["Île-de-France", "Provence-Alpes-Côte d'Azur", "Auvergne-Rhône-Alpes", "Nouvelle-Aquitaine", "Occitanie"],
  Portugal: ["Lisboa", "Porto", "Faro", "Coimbra", "Braga"],
  Italia: ["Lazio", "Lombardia", "Campania", "Sicilia", "Veneto"],
  Alemania: ["Baviera", "Baden-Wurtemberg", "Renania del Norte-Westfalia", "Hesse", "Berlín"],
  "Reino Unido": ["Inglaterra", "Escocia", "Gales", "Irlanda del Norte"],
  "Estados Unidos": ["California", "Texas", "Florida", "Nueva York", "Pensilvania"],
  México: ["Ciudad de México", "Jalisco", "Nuevo León", "Puebla", "Guanajuato"],
  Argentina: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán"],
  Chile: ["Región Metropolitana", "Valparaíso", "Biobío", "Araucanía", "Los Lagos"],
  Colombia: ["Bogotá D.C.", "Antioquia", "Valle del Cauca", "Atlántico", "Santander"],
  Perú: ["Lima", "Arequipa", "La Libertad", "Cusco", "Piura"],
}
