
// @ts-nocheck
import { createClient } from "@supabase/supabase-js"
import * as dotenv from "dotenv"
import path from "path"
import fs from "fs"

const envPath = path.resolve(process.cwd(), ".env.local")
if (fs.existsSync(envPath)) {
    const envConfig = dotenv.parse(fs.readFileSync(envPath))
    for (const k in envConfig) {
        process.env[k] = envConfig[k]
    }
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
const supabase = createClient(supabaseUrl, supabaseKey)

async function checkGenerated() {
    // We try to query information_schema for generated columns
    const { data: cols, error } = await supabase.rpc('get_table_columns_detailed', { table_name: 'price_master' })

    if (error) {
        console.log("RPC failed or not found. Trying raw query via select and error catching.")
        // If we can't use RPC, we'll try to insert a dummy and see error if we want, 
        // but better try to just list and guess based on common patterns.
        // Actually, let's try to query information_schema via a trick if possible, 
        // but Supabase usually doesn't allow direct SELECT on information_schema from anon/service key without specialized RPC.

        // Let's just look at the list of columns again and try to be safe.
        // In most of these "Presupuestalo" projects, base_price and final_price are sums.
        return
    }

    console.log("DETAILED COLS:", JSON.stringify(cols, null, 2))
}

// Since I don't have the RPC, let's just make a script that tries to find which columns are generated by trial and error if needed, 
// OR just assume base_price and final_price are generated since that's what the error said for base_price.

async function guessGenerated() {
    const { data: row } = await supabase.from("price_master").select("*").limit(1)
    if (row && row.length > 0) {
        console.log("COLS:", Object.keys(row[0]))
    }
}

guessGenerated()
