-- Insertar productos de Amazon para reformas, materiales, herramientas, hogar y decoración
-- Tag de afiliado: presupuestalo-21

-- CATEGORÍA: HERRAMIENTAS ELÉCTRICAS
INSERT INTO amazon_products (asin, name, description, price, category, subcategory, image_url, affiliate_url, rating, reviews_count, brand, tags) VALUES
-- Actualizado tag de afiliado a presupuestalo-21 en todas las URLs
('B07VQKZ8YZ', 'Taladro Percutor Bosch Professional GSB 13 RE', 'Taladro percutor de 600W con maletín y accesorios. Ideal para bricolaje y reformas.', 89.99, 'herramientas', 'taladros', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07VQKZ8YZ?tag=presupuestalo-21', 4.6, 3245, 'Bosch', ARRAY['taladro', 'percutor', 'bosch', 'profesional']),
('B08XYQR9ZM', 'Atornillador Eléctrico Makita DF333DWAE', 'Atornillador inalámbrico 12V con 2 baterías y cargador. Compacto y potente.', 129.00, 'herramientas', 'atornilladores', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08XYQR9ZM?tag=presupuestalo-21', 4.7, 1892, 'Makita', ARRAY['atornillador', 'inalámbrico', 'makita', 'batería']),
('B07ZYNQM4K', 'Sierra Circular Einhell TC-CS 1400', 'Sierra circular 1400W con disco de 190mm. Perfecta para cortes precisos.', 69.95, 'herramientas', 'sierras', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07ZYNQM4K?tag=presupuestalo-21', 4.5, 2156, 'Einhell', ARRAY['sierra', 'circular', 'einhell', 'corte']),
('B08FXYZ123', 'Amoladora Angular Bosch GWS 7-125', 'Amoladora de 720W con disco de 125mm. Ideal para cortar y pulir.', 54.90, 'herramientas', 'amoladoras', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08FXYZ123?tag=presupuestalo-21', 4.6, 1567, 'Bosch', ARRAY['amoladora', 'angular', 'bosch', 'corte']),

-- CATEGORÍA: MATERIALES DE CONSTRUCCIÓN
('B09MNOP456', 'Cemento Gris Rápido 5kg', 'Cemento de fraguado rápido para reparaciones urgentes. Listo en 10 minutos.', 12.50, 'materiales', 'cemento', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09MNOP456?tag=presupuestalo-21', 4.4, 892, 'Ceys', ARRAY['cemento', 'rápido', 'reparación']),
('B07PQRS789', 'Yeso Fino para Enlucir 5kg', 'Yeso fino de alta calidad para acabados perfectos en paredes y techos.', 8.95, 'materiales', 'yeso', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07PQRS789?tag=presupuestalo-21', 4.3, 654, 'Pladur', ARRAY['yeso', 'enlucir', 'acabado']),
('B08STUV012', 'Adhesivo para Azulejos 20kg', 'Adhesivo cementoso C2 para cerámica y porcelánico. Interior y exterior.', 24.90, 'materiales', 'adhesivos', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08STUV012?tag=presupuestalo-21', 4.5, 1234, 'Weber', ARRAY['adhesivo', 'azulejos', 'cerámica']),

-- CATEGORÍA: PINTURA Y DECORACIÓN
('B09WXYZ345', 'Pintura Plástica Blanca Mate 15L', 'Pintura lavable de alta cobertura. Ideal para interiores. Rendimiento: 100m²/15L.', 45.99, 'pintura', 'interior', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09WXYZ345?tag=presupuestalo-21', 4.6, 2341, 'Bruguer', ARRAY['pintura', 'blanca', 'mate', 'interior']),
('B07ABC678', 'Rodillo Antigota Premium 25cm', 'Rodillo de microfibra antigota con mango telescópico. Acabado profesional.', 18.50, 'pintura', 'accesorios', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07ABC678?tag=presupuestalo-21', 4.7, 1876, 'Nespoli', ARRAY['rodillo', 'pintura', 'antigota']),
('B08DEF901', 'Esmalte Sintético Brillante Blanco 750ml', 'Esmalte de secado rápido para madera y metal. Resistente a la intemperie.', 14.95, 'pintura', 'esmaltes', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08DEF901?tag=presupuestalo-21', 4.5, 987, 'Titanlux', ARRAY['esmalte', 'brillante', 'madera', 'metal']),

-- CATEGORÍA: FONTANERÍA
('B09GHI234', 'Grifo Monomando Cocina Extraíble', 'Grifo cromado con caño alto giratorio y ducha extraíble. Instalación fácil.', 79.90, 'fontaneria', 'griferia', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09GHI234?tag=presupuestalo-21', 4.6, 1543, 'Grohe', ARRAY['grifo', 'cocina', 'extraíble', 'cromado']),
('B07JKL567', 'Kit Reparación Cisterna Universal', 'Kit completo con mecanismo de descarga y flotador. Compatible con la mayoría de cisternas.', 22.50, 'fontaneria', 'sanitarios', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07JKL567?tag=presupuestalo-21', 4.4, 876, 'Roca', ARRAY['cisterna', 'reparación', 'wc']),
('B08MNO890', 'Tubo Flexible Inoxidable 1/2" 100cm', 'Latiguillo flexible para agua con rosca 1/2". Acero inoxidable trenzado.', 8.95, 'fontaneria', 'tuberias', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08MNO890?tag=presupuestalo-21', 4.5, 1234, 'Sanitop', ARRAY['latiguillo', 'flexible', 'inoxidable']),

-- CATEGORÍA: ELECTRICIDAD
('B09PQR123', 'Caja 100 Enchufes Schuko Blancos', 'Enchufes con toma de tierra 16A. Incluye marco y mecanismo completo.', 12.90, 'electricidad', 'mecanismos', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09PQR123?tag=presupuestalo-21', 4.5, 765, 'Simon', ARRAY['enchufe', 'schuko', 'blanco']),
('B07STU456', 'Regleta Protección 6 Tomas + USB', 'Regleta con protección contra sobretensiones. 2 puertos USB de carga rápida.', 19.95, 'electricidad', 'regletas', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07STU456?tag=presupuestalo-21', 4.7, 2134, 'Belkin', ARRAY['regleta', 'protección', 'usb']),
('B08VWX789', 'Bombillas LED E27 10W Pack 10', 'Bombillas LED luz cálida 3000K. Equivalente a 75W. Ahorro del 85%.', 24.90, 'electricidad', 'iluminacion', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08VWX789?tag=presupuestalo-21', 4.6, 3456, 'Philips', ARRAY['bombilla', 'led', 'e27', 'ahorro']),

-- CATEGORÍA: CARPINTERÍA
('B09YZA012', 'Bisagras Cazoleta 35mm Pack 20', 'Bisagras de cazoleta con cierre suave. Incluye tornillos y plantilla de montaje.', 29.90, 'carpinteria', 'herrajes', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09YZA012?tag=presupuestalo-21', 4.5, 987, 'Blum', ARRAY['bisagra', 'cazoleta', 'cierre suave']),
('B07BCD345', 'Tirador Mueble Acero Inox 128mm Pack 10', 'Tiradores modernos de acero inoxidable cepillado. Diseño minimalista.', 16.50, 'carpinteria', 'tiradores', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07BCD345?tag=presupuestalo-21', 4.6, 1234, 'Emuca', ARRAY['tirador', 'inoxidable', 'moderno']),
('B08EFG678', 'Barniz Madera Satinado 750ml', 'Barniz al agua de secado rápido. Protección UV. Interior y exterior.', 19.95, 'carpinteria', 'acabados', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08EFG678?tag=presupuestalo-21', 4.5, 876, 'Xylazel', ARRAY['barniz', 'madera', 'satinado']),

-- CATEGORÍA: HOGAR Y DECORACIÓN
('B09HIJ901', 'Espejo Baño LED 80x60cm', 'Espejo con iluminación LED integrada y antivaho. Interruptor táctil.', 129.00, 'hogar', 'espejos', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09HIJ901?tag=presupuestalo-21', 4.7, 1567, 'Talos', ARRAY['espejo', 'led', 'baño', 'antivaho']),
('B07KLM234', 'Cortina Ducha Antimoho 180x200cm', 'Cortina de baño impermeable con tratamiento antimoho. Incluye 12 anillas.', 15.90, 'hogar', 'textil', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07KLM234?tag=presupuestalo-21', 4.4, 2345, 'Amazon Basics', ARRAY['cortina', 'ducha', 'antimoho']),
('B08NOP567', 'Alfombra Salón Moderna 160x230cm', 'Alfombra de pelo corto diseño geométrico. Fácil limpieza y antideslizante.', 89.90, 'hogar', 'alfombras', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08NOP567?tag=presupuestalo-21', 4.6, 987, 'Carpeto', ARRAY['alfombra', 'moderna', 'geométrica']),
('B09QRS890', 'Lámpara Techo LED Regulable 48W', 'Plafón LED con mando a distancia. Temperatura de color ajustable 3000K-6500K.', 59.90, 'hogar', 'iluminacion', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09QRS890?tag=presupuestalo-21', 4.7, 1876, 'Anten', ARRAY['lámpara', 'led', 'regulable', 'techo']),
('B07TUV123', 'Estantería Pared Flotante 80cm Pack 3', 'Estanterías de madera con soporte invisible. Carga máxima 15kg por balda.', 34.90, 'hogar', 'almacenaje', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07TUV123?tag=presupuestalo-21', 4.5, 1234, 'WOLTU', ARRAY['estantería', 'flotante', 'madera']),

-- CATEGORÍA: SEGURIDAD Y PROTECCIÓN
('B08WXY456', 'Detector Humo Fotoeléctrico Pack 4', 'Detectores de humo con batería de 10 años. Certificación EN14604.', 39.90, 'seguridad', 'detectores', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08WXY456?tag=presupuestalo-21', 4.6, 2134, 'X-Sense', ARRAY['detector', 'humo', 'seguridad']),
('B09ZAB789', 'Cerradura Inteligente Bluetooth', 'Cerradura digital con apertura por huella, código y app móvil. Batería recargable.', 149.00, 'seguridad', 'cerraduras', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09ZAB789?tag=presupuestalo-21', 4.5, 876, 'Yale', ARRAY['cerradura', 'inteligente', 'huella']),

-- CATEGORÍA: JARDÍN Y EXTERIOR
('B07CDE012', 'Manguera Jardín Extensible 30m', 'Manguera flexible que se expande hasta 30m. Incluye pistola con 7 modos de riego.', 34.90, 'jardin', 'riego', 'https://m.media-amazon.com/images/I/61xKZqN8xyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B07CDE012?tag=presupuestalo-21', 4.4, 1567, 'Gardena', ARRAY['manguera', 'extensible', 'riego']),
('B08FGH345', 'Foco LED Exterior 50W con Sensor', 'Proyector LED con detector de movimiento. IP65 resistente al agua.', 29.90, 'jardin', 'iluminacion', 'https://m.media-amazon.com/images/I/71qvLNqfVyL._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B08FGH345?tag=presupuestalo-21', 4.6, 2345, 'Lepro', ARRAY['foco', 'led', 'exterior', 'sensor']),
('B09IJK678', 'Césped Artificial 2x5m Altura 30mm', 'Césped sintético de alta densidad. Drenaje rápido y resistente a UV.', 89.90, 'jardin', 'cesped', 'https://m.media-amazon.com/images/I/71YqN8ZQKML._AC_SL1500_.jpg', 'https://www.amazon.es/dp/B09IJK678?tag=presupuestalo-21', 4.5, 987, 'CASA PURA', ARRAY['césped', 'artificial', 'jardín']);
