export const dynamic = "force-dynamic"
import { type NextRequest, NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { generateText } from "ai"
import { groqProvider, FAST_GROQ_MODEL } from "@/lib/ia/groq"
import * as fal from "@fal-ai/serverless-client"

// Configure FAL client
fal.config({
  credentials: process.env.FAL_KEY,
})

async function generateRenderWithFal(originalImageUrl: string, prompt: string): Promise<string> {
  try {
    console.log("[v0] Generating photorealistic render with FAL.ai (Image-to-Image)")

    const result: any = await fal.subscribe("fal-ai/flux/dev/image-to-image", {
      input: {
        image_url: originalImageUrl,
        prompt: prompt,
        strength: 0.7, // Maintain structure but add realistic textures and furniture
        num_inference_steps: 28,
        guidance_scale: 3.5,
        num_images: 1,
      },
      logs: true,
    })

    const images = result?.images || result?.data?.images
    if (!images || images.length === 0) {
      throw new Error("No image generated by FAL")
    }

    return images[0].url
  } catch (error) {
    console.error("[v0] FAL generation error:", error)
    throw error
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    if (!supabase) {
      return NextResponse.json({ error: "Configuración de servidor incompleta" }, { status: 500 })
    }

    const {
      data: { session },
    } = await supabase.auth.getSession()

    if (!session) {
      return NextResponse.json({ error: "No autorizado" }, { status: 401 })
    }

    const formData = await request.formData()
    const imageFile = formData.get("image") as File
    const materialsStr = formData.get("materials") as string
    const style = formData.get("style") as string
    const details = formData.get("details") as string

    if (!imageFile) {
      return NextResponse.json({ error: "Imagen requerida" }, { status: 400 })
    }

    // Convert image to base64 for FAL and Groq
    const imageBuffer = await imageFile.arrayBuffer()
    const imageBase64 = Buffer.from(imageBuffer).toString("base64")
    const imageMimeType = imageFile.type
    const originalImageUrl = `data:${imageMimeType};base64,${imageBase64}`

    // Parse materials
    const materials = materialsStr ? JSON.parse(materialsStr) : []

    // 1. Refine prompt with Groq (Translate and add architectural context)
    console.log("[v0] Refining render prompt with Groq...")
    const { text: refinedPrompt } = await generateText({
      model: groqProvider(FAST_GROQ_MODEL),
      prompt: `Translate and refine this interior design render request into a detailed English prompt for an AI image generator (Flux).
        The goal is to transform a 2D floor plan into a HIGH QUALITY photorealistic top-down architectural visualization render.
        
        Style: ${style || "modern"}
        Materials to include: ${materials.join(", ") || "None"}
        User Details: ${details || "None"}
        
        Requirements:
        - View: COMPLETELY TOP-DOWN (Bird's eye view), exactly perpendicular to the floor.
        - Look: 8k, fotorrealistic, professional architectural photography.
        - Lighting: Soft natural sunlight with realistic shadows.
        - Elements: Add realistic furniture, rugs, plants, kitchens, and bathroom fixtures.
        - Structure: Keep the exact walls and layout from the original plan.
        
        Respond ONLY with the English prompt.`,
    })

    // 2. Generate render with FAL
    const finalImageUrl = await generateRenderWithFal(originalImageUrl, refinedPrompt)

    const render = {
      id: Math.random().toString(36).substring(7),
      imageUrl: finalImageUrl,
      prompt: `Render fotorrealista profesional con ${materials.length > 0 ? "materiales personalizados" : "acabados de calidad"}${style ? ` en estilo ${style}` : ""}`,
      timestamp: new Date().toLocaleString("es-ES", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      }),
    }

    return NextResponse.json({ render })
  } catch (error) {
    console.error("[v0] Error generating render:", error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Error al generar render" },
      { status: 500 },
    )
  }
}
